#!/bin/bash

source /opt/conda/bin/activate py37
export PYTHONPATH=/scratch1/liam.bindle/sg-TROPOMI/TROPOMI_data/tessellate

TROPOMI_TESSELATION_ARGS="--grid_in_cxy LON_CENTER,LAT_CENTER --grid_in_xy LON_CORNERS,LAT_CORNERS --grid_out comparison_grid.nc --grid_out_cxy grid_boxes_centers --grid_out_xy grid_boxes --extent -128 -65 23 50"
GCHP_TESSELATION_ARGS="--grid_in_cxy grid_boxes_centers --grid_in_xy grid_boxes --grid_out comparison_grid.nc --grid_out_cxy grid_boxes_centers --grid_out_xy grid_boxes --extent -128 -65 23 50"
TROPOMI_SAMPLE=/scratch1/liam.bindle/sg-TROPOMI/GOOD_RUNS/tropomi_sample_data

eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180701.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180701.npz &> 1.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180702.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180702.npz &> 2.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180703.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180703.npz &> 3.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180704.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180704.npz &> 4.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180705.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180705.npz &> 5.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180706.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180706.npz &> 6.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180707.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180707.npz &> 7.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180708.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180708.npz &> 8.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180709.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180709.npz &> 9.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180710.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180710.npz &> 10.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180711.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180711.npz &> 11.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180712.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180712.npz &> 12.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180713.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180713.npz &> 13.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180714.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180714.npz &> 14.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180715.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180715.npz &> 15.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180716.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180716.npz &> 16.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180717.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180717.npz &> 17.txt &
wait
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180718.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180718.npz &> 18.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180719.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180719.npz &> 19.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180720.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180720.npz &> 20.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180721.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180721.npz &> 21.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180722.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180722.npz &> 22.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180723.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180723.npz &> 23.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180724.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180724.npz &> 24.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180725.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180725.npz &> 25.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180726.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180726.npz &> 26.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180727.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180727.npz &> 27.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180728.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180728.npz &> 28.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180729.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180729.npz &> 29.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180730.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180730.npz &> 30.txt &
eval python -m tessellate.generate --grid_in ${TROPOMI_SAMPLE}/updated_NEI11_hourly_20180731.nc ${TROPOMI_TESSELATION_ARGS} -o TROPOMI.tessellation.20180731.npz &> 31.txt &

eval python -m tessellate.generate --grid_in C180_global.nc ${GCHP_TESSELATION_ARGS} -o C180_global.tessellation.npz &> 32.txt &
eval python -m tessellate.generate --grid_in C180e_NA.nc ${GCHP_TESSELATION_ARGS} -o C180e_NA.tessellation.npz &> 33.txt &
eval python -m tessellate.generate --grid_in C720e_CA.nc ${GCHP_TESSELATION_ARGS} -o C720e_CA.tessellation.npz &> 34.txt &
wait