#!/bin/bash

source /opt/conda/bin/activate py37
export PYTHONPATH=/scratch1/liam.bindle/sg-TROPOMI/TROPOMI_data/tessellate

FNAME_TEMPLATE=$1

DATES=(20180701 20180702 20180703 20180704 20180705 20180706 20180707 20180708 20180709 20180710 20180711 20180712 20180713 20180714 20180715 20180716 20180717 20180718 20180719 20180720 20180721 20180722 20180723 20180724 20180725 20180726 20180727 20180728 20180729 20180730 20180731)
TESSELLATIONS_PATH=/scratch1/liam.bindle/sg-TROPOMI/GOOD_RUNS/tesselations

for date in ${DATES[@]}; do
    eval python -m tessellate.compute --grid_in $FNAME_TEMPLATE --input $FNAME_TEMPLATE --grid_in_cxy LON_CENTER,LAT_CENTER --grid_out $TESSELLATIONS_PATH/comparison_grid.nc --grid_out_cxy grid_boxes_centers --matrix $TESSELLATIONS_PATH/TROPOMI.tessellation.${date}.npz --drop LAT_CORNERS LON_CORNERS LAT_CENTER LON_CENTER -o TROPOMI_NO2.${date}.nc
done

source /opt/conda/bin/activate py36
export PYTHONPATH=/scratch1/liam.bindle/sg-ensemble-2/sg-restart-regridder/:/scratch1/gcpy

python -m sg.nanaverage TROPOMI_NO2.201807* --weekly --dim time --missing_time -o TROPOMI_NO2_July2018_weekly.nc
python -m sg.nanaverage TROPOMI_NO2.201807* --dim time --missing_time -o TROPOMI_NO2_July2018.nc