#!/bin/bash

source /opt/conda/bin/activate py37
export PYTHONPATH=/scratch1/liam.bindle/sg-TROPOMI/TROPOMI_data/tessellate

for var in "$@"
do
	date=$(echo updated_NEI11_hourly_20180701.nc  | egrep -o '2018[0-9]{4}')
	python -m tessellate.generate --grid_in ${var} --grid_in_cxy LON_CENTER,LAT_CENTER --grid_in_xy LON_CORNERS,LAT_CORNERS --grid_out comparison_grid.nc --grid_out_cxy grid_boxes_centers --grid_out_xy grid_boxes --weight_by_ibox --extent -128 -65 23 50 -o tesselation
done

python -m tessellate.generate --grid_in updated_NEI11_hourly_20180701.nc --grid_in_cxy LON_CENTER,LAT_CENTER --grid_in_xy LON_CORNERS,LAT_CORNERS --grid_out grid_box_outlines_and_centers.nc --grid_out_cxy grid_boxes_centers --grid_out_xy grid_boxes --weight_by_ibox --extent -128 -65 23 50 -o TROPOMI_tessellation_20180701.npz
python -m tessellate.compute  --grid_in updated_NEI11_hourly_20180701.nc --input updated_NEI11_hourly_20180701.nc --grid_in_cxy LON_CENTER,LAT_CENTER --grid_out grid_box_outlines_and_centers.nc --grid_out_cxy grid_boxes_centers --matrix TROPOMI_tessellation_20180701.npz --drop LAT_CORNERS LON_CORNERS LAT_CENTER LON_CENTER -o test_TROPOMI_20180701.nc
